#!/usr/bin/env node
// Bundle algorithms; React and Harness packages remain supplied by the host.
import { build } from 'esbuild';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
const root = fileURLToPath(new URL('..', import.meta.url));
const pkg = JSON.parse(await readFile(join(root, 'package.json'), 'utf8'));
const result = await build({ entryPoints: [join(root, 'client/index.js')], bundle: true, write: false,
  format: 'cjs', platform: 'browser', target: ['chrome134'], external: ['react', '@deepseek-ai/*'],
  legalComments: 'inline', minify: false });
const output = `// Generated by client/build.mjs. Edit client/ sources, then rebuild.\nwindow.__ModuleLoader__.load({ id: ${JSON.stringify(pkg.name)}, factory: (require) => {\nvar module = { exports: {} }; var exports = module.exports;\n${result.outputFiles[0].text}\nreturn module.exports; } });\n`;
const destination = join(root, 'lib/client.js');
await mkdir(dirname(destination), { recursive: true });
await writeFile(destination, output);
console.log(`客户端插件已构建：${destination} (${(Buffer.byteLength(output) / 1024).toFixed(1)} KB)`);
